version: "3.3"
services:

  reqhack-server:
    build:
      context: ./server
    ports:
      - 8081:8081
    links:
      - database
    environment:
      - DB_NAME=reqhack
      - REQHACK_BASEHOST
      - DATA_SOURCE_NAME=root:${MYSQL_ROOT_PASSWORD}@tcp(database:3306)/reqhack
      - REQHACK_RANDOM

  database:
    image: mysql
    volumes:
      - ./mysql/conf.d/nativepassword.cnf:/etc/mysql/conf.d/nativepassword.cnf
      - ./mysql/init/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
  nginx:
    build:
      context: ./client
      args:
        - REQHACK_BASEHOST=${REQHACK_BASEHOST}
        - REQHACK_USE_SSL=${REQHACK_USE_SSL}
        - REQHACK_RANDOM=${REQHACK_RANDOM}
    ports:
      - 80:80
      - 443:443
    environment:
      - REQHACK_BASEHOST
      - REQHACK_RANDOM
    links:
      - reqhack-server
    volumes:
      - ./nginx/:/var/log/nginx/
      - /var/lib/waagent/${REQHACK_CERT}:/etc/nginx/ssl/cert.crt
      - /var/lib/waagent/${REQHACK_PRIVATE}:/etc/nginx/ssl/cert.prv
