version: "3"
services:
  reqhack-server:
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/go/src/github.com/KageShiron/reqhack/server
    links:
      - database
    environment:
      - DB_NAME=reqhack
      - DATA_SOURCE_NAME=root:mysql@tcp(database:3306)/reqhack
    entrypoint: ["./wait-for-it.sh","database:3306","--","/go/bin/server"]

  database:
    image: mysql
    volumes:
      - ./server/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=reqhacker
      - MYSQL_PASSWORD=reqhacker

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    environment:
      - REQHACK_BASEHOST
    links:
      - reqhack-server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf.template
      - /etc/nginx/ssl/:/etc/nginx/ssl/
    command: /bin/bash -c "export REQHACK_BASEHOST_ESC=$$(echo $REQHACK_BASEHOST | sed '-e s/\./\\\\./g') && echo $$REQHACK_BASEHOST && echo $$REQHACK_BASEHOST_ESC && envsubst '$$REQHACK_BASEHOST,$$REQHACK_BASEHOST_ESC' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
