version: "3.5"
services:

  reqhack-server:
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/go/src/github.com/KageShiron/reqhack/server
    links:
      - database
    environment:
      - DB_NAME=reqhack
      - DATA_SOURCE_NAME=root:mysql@tcp(database:3306)/reqhack
      - REQHACK_BASEHOST
      - REQHACK_RANDOM
    entrypoint: ["./wait-for-it.sh","database:3306","--","/go/bin/server"]

  database:
    image: mysql
    volumes:
      - ./server/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=reqhacker
      - MYSQL_PASSWORD=reqhacker
  nginx:
    build:
      context: ./client
      args:
        - REQHACK_BASEHOST=${REQHACK_BASEHOST}
        - REQHACK_USE_SSL=${REQHACK_USE_SSL}
        - REQHACK_RANDOM=${REQHACK_RANDOM}
    ports:
      - 80:80
      - 443:443
    environment:
      - REQHACK_BASEHOST
      - REQHACK_RANDOM
    links:
      - reqhack-server
    volumes:
      - /var/lib/waagent/${REQHACK_CERT}:/etc/nginx/ssl/cert.crt
      - /var/lib/waagent/${REQHACK_PRIVATE}:/etc/nginx/ssl/cert.prv